### ISSUE TITLE
[2.0] What should the default dispatcher for execute functions be?

### ISSUE THREAD

**Issue by gpeal** [airbnb/mavericks#404]
Jetpack is using Dispatchers.Main.immediate for the default dispatcher for things like `viewModelScope` and thus, we have adopted that as our default for `viewModelScope`. We also need to pick a default dispatcher for `execute`. Each default has pros and cons:
`Main.immediate`
* Decent expectation for a default on Android
* Would work if the underlying library ensured that IO operations are done in the correct scope using `withContext`. I believe Room does this.
`Dispatchers.IO`
* What most situations would want but may be presumptuous as a default
`Dispatchers.Default`
* Has default in the name but if `IO` is what people often want, it could cause many IO operations to be run on the `Default` dispatcher.

@BenSchwab @elihart @denis-bezrukov

**Comment by elihart** [comment]
why is `could cause many IO operations to be run on the Default dispatcher.` applied as a con to Dispatchers.Default but not to `Dispatchers.Main.immediate`? It seems like someone could misuse either one for IO.

What cases besides IO might somebody not want to use `Dispatchers.Default`? Don't we want to encourage that nothing done in the viewmodel relates to UI and/or the main thread?

Is `Dispatchers.Main.immediate` really a decent expectation for default? If I do something like this in my viewmodel I would expect it to run off the main thread
```
viewModelScope.launch {
  // some expensive code
}
```

**Comment by gpeal** [comment]
@elihart Android will throw a network/db on main exception if it gets used incorrectly.
@elihart The expectation from anybody used to a Jetpack ViewModel is that it would be on Main. Operations that to db/network should use `withContext(Dispatchers.IO)` as close to the IO operation as possible so it actually shouldn't matter for most cases if the suspend fun does the right thing.

**Comment by denis-bezrukov** [comment]
@gpeal one weird thing I've often encountered lately - is network/room exception are swallowed because of SupervisorJob / execute's try-catch, so it's easy to write something like
```
suspend { 
   dao.queryToDb()
}.execute { copy(...) }
```
and then debug it for a while to understand why it doesn't display the data correctly. For VMs with debugMode = true we could crash the app asap for the NetworkOnMainThreadEx/SQLIte main thread exceptions.

**Comment by gpeal** [comment]
@denis-bezrukov yeah, that has happened to me too. That could be investigated as part of https://github.com/airbnb/MvRx/issues/389

Any thoughts on the default dispatcher?

**Comment by Minirogue** [comment]
I would expect `Dispatchers.Default` for a call restricted to the viewmodel. I'm actually surprised to learn that `viewModelScope` is built with `Dispatchers.Main.immediate`

**Comment by Namnodorel** [comment]
I was quite surprised to learn that `execute()`, a function that is to be used with a component named `Async` actually uses the main thread by default.

I think the default Dispatcher should be `Dispatchers.Default`, since a generic asynchronous Dispatcher is the thing I would intuitively expect from a code block that executes some stuff in a different thread/coroutine without specifying which. Though I agree that IO is the most common use case, it seems more readable and intuitive to me to always explicitly mark code that needs a specialized IO Dispatcher/thread as such.

**Comment by gpeal** [comment]
@Namnodorel On the flip side, suspending functions usually handle their own dispatchers internally. For example, Retrofit and Room both use their own dispatchers so adding IO here would actually just slow things down because it's going to get re-dispatched internally by those libraries anyway.

**Comment by Minirogue** [comment]
After coming back around to this. I can see why the main dispatcher would be used by default. Specifically, testing coroutines correctly usually involves injecting dispatchers and calling [setMain](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/kotlinx.coroutines.-dispatchers/set-main.html). This means that any coroutine contexts not owned by the tested class should either be able to be injected with a dispatcher or should use the main dispatcher by default.

As for the original question of this issue. Having just converted from MvRx 1.x to Mavericks 2.x, I'd say that I expect `MavericksViewModel.viewModelScope` and `ViewModel.viewModelScope` to behave as close to the same as possible. So, I think the main dispatcher is the correct choice. If I really want to make sure that some piece of code is run off of the main thread, then I'll be declaring that fact explicitly by selecting the dispatcher myself (or deferring to the library's dispatchers).

**Comment by gpeal** [comment]
@Minirogue Agreed!

**Comment by gpeal** [comment]
Closing this out because 2.0 has been released with Dispatchers.Main
