### ISSUE TITLE
(Better) Support for Jetpack Compose

### ISSUE THREAD

**Issue by Namnodorel** [airbnb/mavericks#437]
I've been using MvRx (stable release) with Jetpack Compose in a recent project, and although it is possible to simply call `setContent()` every time `invalidate()` gets called, that's not really the "Compose way" of doing things. Compose already has handy shortcuts for accessing state from `LiveData` and `RxJava2`, and it would be nice if there was a MvRx equivalent, like `viewModel.subscribeAsState()` that could completely avoid `invalidate`. 

The implementation of this for RxJava2 can be seen [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:compose/runtime/runtime-rxjava2/src/main/java/androidx/compose/runtime/rxjava2/RxJava2Adapter.kt;l=44) and it seems to me like it would be pretty easy to adapt that for MvRx.

**Comment by elihart** [comment]
In our upcoming 2.0 release (currently in alpha) we expose a coroutine Flow of state changes - I think ideally composable functions would take a state flow as a parameter?

**Comment by gpeal** [comment]
@Namnodorel With the addition of `stateFlow` in MvRx 2, can we close this?

**Comment by Namnodorel** [comment]
I'm not sure, I am not very familiar with the changes in 2.0 yet. Will take a closer look tomorrow.

**Comment by Dugin123** [comment]
JetPackCompose need kotlin 1.4 .
https://github.com/airbnb/MvRx/issues/433

**Comment by Namnodorel** [comment]
Indeed, `stateFlow` provides an elegant solution to the issue. Thank you!

**Comment by THEAccess** [comment]
`stateFlow` works fine. However, because you need to provide an initial state I ended up using something like ` val state by viewModel.stateFlow.collectAsState(AState())` all over the place, which is very ugly. Has someone found a better solution to this?
`

**Comment by gpeal** [comment]
@THEAccess Yea, I've been playing around with this a bit. Hopefully we'll have an official recommendation soon but this is one potential solution I came up with

https://gist.github.com/gpeal/5bed618a843d4d71bb1518fa8317c5df

**Comment by kaushalyap** [comment]
@gpeal Can we use MvRx with [Compose without fragments and Navigation component](https://developer.android.com/jetpack/compose/navigation)?

**Comment by gpeal** [comment]
@kaushalyap Yes, it just requires a `LifecycleOwnerAmbient`, it has no dependency on an Activity or Fragment.

**Comment by kaushalyap** [comment]
> Yes, it just requires a LifecycleOwnerAmbient, it has no dependency on an Activity or Fragment.

@gpeal  glad to hear! Any example code and docs would be great

**Comment by kaushalyap** [comment]
@gpeal Any plans with Compose Support (including Compose Navigation) now Compose has reached Beta?

**Comment by gpeal** [comment]
@kaushalyap The gist is still the closest thing. I've updated the APIs to reflect some new Compose APIs and it is working great in the Lottie sample app. Feel free to copy the code from it into your own project. You'll need to set a compiler flag like [this](https://github.com/airbnb/lottie-android/blob/master/sample-compose/build.gradle#L40) to use some of the internal Mavericks APIs that it uses though.

**Comment by pwillmann** [comment]
The gist works great when using Compose in a Fragment or `FragmentActivity` but `ComponentActivity` is not supported yet. Would be great if that would also work so no traditional AndroidX imports are needed anymore. This requires some more changes though I think.
