### ISSUE TITLE
How do I use MockableMavericksView in Activity？

### ISSUE THREAD

**Issue by caiyoufei** [airbnb/mavericks#456]
version is 2.0.0-beta1

**Comment by elihart** [comment]
I'm not sure what you mean exactly. Do you want to mock your activity or show mocks inside the activity?

generally you would use `MockableMavericksView` as a replacement for `MavericksView`, where ever you would use that. Mocking an Activity isn't really supported right now, the main use case that is supported is Fragments (or custom views that implement MavericksView)

**Comment by caiyoufei** [comment]
I use MockableMavericksView in fragment is OK，But "Don't know how to get Context from mavericks view ..." error will be thrown in Activity

**Comment by caiyoufei** [comment]
In the Demo, there is no example of using MockableMavericksView in Activity

**Comment by caiyoufei** [comment]
I want use it in Activity like this:
~~~
package com.airbnb.mvrx.sample

import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import com.airbnb.mvrx.MavericksState
import com.airbnb.mvrx.MavericksView
import com.airbnb.mvrx.sample.core.MvRxViewModel
import com.airbnb.mvrx.viewModel
import com.airbnb.mvrx.withState

data class ViewModelMainState(val name: String = "this is original name") : MavericksState {
}
class ViewModelMainModel(initialState: ViewModelMainState) : MvRxViewModel<ViewModelMainState>(initialState) {
    fun setCount(nameNew: String) = setState { copy(name = nameNew) }
}
class MainActivity : AppCompatActivity(), MavericksView {
    private val viewModel: ViewModelMainModel by viewModel()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        viewModel.setCount("this is new name")
    }
    override fun invalidate(): Unit =  withState(viewModel) { state ->
        Log.e("MainActivity", "MainActivity:${state.name}")
    }
}
~~~

**Comment by elihart** [comment]
the `viewModel` function you are using acts on an Activity, not on `MavericksView`.  MavericksView was designed around fragments, not activities

**Comment by caiyoufei** [comment]
The previous version uses MvRxView. Calling copy data in MvRxViewModel can trigger invalidate, but I don’t know how to trigger invalidate in the latest version.

**Comment by gpeal** [comment]
@caiyoufei Same way as before
https://github.com/airbnb/MvRx/blob/release/2.0.0/mvrx/src/main/kotlin/com/airbnb/mvrx/MavericksView.kt#L75

**Comment by caiyoufei** [comment]
Use copy in MvRxViewModel does not call postInvalidate。
So I don’t know how to use it in the new version。

**Comment by gpeal** [comment]
@caiyoufei I don't follow

**Comment by iamsr** [comment]
you can extend the MavericksView for the activity. It won't call invalidate function but you can register onEach on the ViewModel and get the updates triggered on state change.
