### ISSUE TITLE
docs error: mavericks-rxjava2 vs mvrx-rxjava2

### ISSUE THREAD

**Issue by Minirogue** [airbnb/mavericks#511]
The [docs for upgrading from mvrx 1](https://airbnb.io/mavericks/#/new-2x?id=upgrading) say to use the `mvrx-rxjava2` artifact when upgrading, but that didn't resolve for me. `mavericks-rxjava2` did, however.

**Comment by elihart** [comment]
Thanks for reporting, updated the docs with https://github.com/airbnb/mavericks/pull/512
