### ISSUE TITLE
Cannot find mavericks-compose artifact

### ISSUE THREAD

**Issue by itsandreramon** [airbnb/mavericks#520]
The documentation states the following:

"To use Mavericks with Jetpack Compose, add the com.airbnb.android:mavericks-compose artifact (TBD on versioning)."

Yet I cannot find the corresponding artifact on MavenCentral. Any idea why? I searched the following: https://mvnrepository.com/artifact/com.airbnb.android

**Comment by gpeal** [comment]
It will be released today :)
