### ISSUE TITLE
[2.x] RxJava BaseMvRxViewModel's execute does not support retainValue

### ISSUE THREAD

**Issue by pwillmann** [airbnb/mavericks#521]
I noticed that that the RxJava's `BaseMvRxViewModel` currently does not support `retainValue` as the `MavericksViewModel` does for the `execute` function. 

While we are working on migrating the codebase to Coroutines, some features are still stuck in the Rx world and it would be great to be able to use this feature for RxJava based ViewModels too. Is this something I can help out with?

**Comment by gpeal** [comment]
@pwillmann I recommend using `kotlinx-coroutines-rx2`. It has `asFlow()` to turn an observable/other rx source into a flow/another coroutines operator.

This has worked extremely well for us at Tonal in the migration from rxjava to Flow. Any time we encounter an Observable in new code, we use `asFlow()` then treat it like we would with a Flow. Eventually, enough consumers of the base observable get migrated that we can just switch the base implementation.

**Comment by pwillmann** [comment]
Thank you! 

That is also the approach I went with and it's working really well. Most of our data/repository layer is still Rx so we end up converting pretty much everything from Observable/Single to Flow/Await.
