### ISSUE TITLE
Subscribing to state class in Compose

### ISSUE THREAD

**Issue by franciscoaleixo** [airbnb/mavericks#529]
There seems to be an opinion on both the docs and the [latest announcement](https://gpeal.medium.com/mavericks-meet-jetpack-compose-cf6721f2ea88) of support for Compose that subscribing to the entire state class is probably wrong, and it is better to subscribe to specific fields. I don't really oppose that subscribing to specific fields can be advantageous in certain cases, but I don't think subscribing to the entire state class is inherently wrong, and the justification given seems to be a bit misleading.

If we use the [@Immutable annotation](https://developer.android.com/reference/kotlin/androidx/compose/runtime/Immutable)  / [@Stable annotation](https://developer.android.com/reference/kotlin/androidx/compose/runtime/Stable) on the state class, it should not trigger recomposition of other (stateless) composables that depend on certain state properties if another state property changes, you can read more on my question and discussion on [this kotlinlang thread](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1615691220166000). I know that Mavericks even checks in debug mode if the state class is immutable, so it _should_ work great with this.

With this in mind, I'm not sure what I even propose or the implications here, maybe a note on the docs about this, maybe it can even be relevant to consider these annotations somehow for MavericksState. I'm opening this mostly for discussion and awareness.

**Comment by gpeal** [comment]
You are right that MavericksState is `@Immutable`. One challenge right now is that using it requires adding compose which the base mavericks artifact doesn't have. I was just chatting with Leland Richardson about making a `compose-common` base artifact that would include these annotations without the rest of Compose and that may happen but it hasn't happened yet.

Regarding collecting the entire state, Compose may be able to skip some child recomposition but it will at minimum have to recompose the composable that collects the state which wouldn't happen if you just collected the state properties you use. That is my understanding at least.

**Comment by franciscoaleixo** [comment]
> You are right that MavericksState is `@Immutable`. One challenge right now is that using it requires adding compose which the base mavericks artifact doesn't have. I was just chatting with Leland Richardson about making a `compose-common` base artifact that would include these annotations without the rest of Compose and that may happen but it hasn't happened yet.

This seems like a great compromise and I think it could be useful for sure.

> Regarding collecting the entire state, Compose may be able to skip some child recomposition but it will at minimum have to recompose the composable that collects the state which wouldn't happen if you just collected the state properties you use. That is my understanding at least.

I don't think this is true, my understanding is that recomposition happens based on the Composable parameters (i.e. if they change), simply injecting the view model and collecting state after composition already happened (i.e. on the composable method's body) will not affect it whatsoever. I think if this happened it would be weird and you'd be resubscribing to the state flow everytime it updated, and [the docs](https://developer.android.com/jetpack/compose/mental-model#recomposition) seem to support it. Although I'm definitely not an expert and please someone correct me if I'm wrong.

Eitherway I just really like having one state and one subscription point per screen, I think it makes things neater and easier to reason about and if I can make it possible I definitely would like to push it here 😛

**Comment by gpeal** [comment]
@franciscoaleixo I think in practice, both will be useful at different times which is why they both exist. You'll need to find a balance for what you need for a given composable which is why both APIs exist. I'm going to go ahead and close this out for now but let me know if you have any questions. We're all collectively learning Compose and establishing best practices together on this one.
