### ISSUE TITLE
Fragment+MvRxView's asyncSubscribe not (quite?) disposed with mavericks-rxjava2

### ISSUE THREAD

**Issue by krage** [airbnb/mavericks#530]
I'm trying out swapping in `mavericks:2.1.0` and `mavericks-rxjava2:2.1.0` on an app with existing screens that were previously using `mvrx:1.5.1`. I've made the changes described in the transition docs and also deleted the explicit `viewLifecycleOwner` first argument in all my uses of `asyncSubscribe` since it's no longer present.

With no other changes I started getting exceptions with the "Subscribing with a duplicate subscription id" error message when navigating forward and then returning back to any fragment that was using `deliveryMode = uniqueOnly()` on a subscription. I looked at a subscription without the unique delivery mode and it seems `isDisposed` on the returned `Disposable` remains false beyond `onDestroyView` back through to the next `onCreateView`. I started adding subscriptions to a list and logging which looks like this on `1.5.1`:

```
onCreateView ⇒ 1 subscriptions created, isDisposed: [false]
onDestroyView ⇒ 1 subscriptions created, isDisposed: [true]
onCreateView ⇒ 2 subscriptions created, isDisposed: [true, false]
onDestroyView ⇒ 2 subscriptions created, isDisposed: [true, true]
onCreateView ⇒ 3 subscriptions created, isDisposed: [true, true, false]
onDestroyView ⇒ 3 subscriptions created, isDisposed: [true, true, true]
```
but now this on `2.1.0`:
```
onCreateView ⇒ 1 subscriptions created, isDisposed: [false]
onDestroyView ⇒ 1 subscriptions created, isDisposed: [false]
onCreateView ⇒ 2 subscriptions created, isDisposed: [false, false]
onDestroyView ⇒ 2 subscriptions created, isDisposed: [false, false]
onCreateView ⇒ 3 subscriptions created, isDisposed: [false, false, false]
onDestroyView ⇒ 3 subscriptions created, isDisposed: [false, false, false]
```
Active subscriptions are now stacking up every time the view lifecycle loops, or in the case where unique delivery mode is requested they're an immediate exception throw at the point where they would be resubscribed. I looked at [the default `subscriptionLifecycleOwner`](https://github.com/airbnb/mavericks/blob/891d640979043af8c2cbe5004d26e2ad43dedb0d/mvrx/src/main/kotlin/com/airbnb/mvrx/MavericksView.kt#L58-L73) and would expect `viewLifecycleOwner` to get used implicitly for `asyncSubscribe` called in `Fragment.onCreateView` here, but also tried overriding it in the fragment to only supply `viewLifecycleOwner` and got the same result.

**Comment by gpeal** [comment]
@krage Mavericks ViewModel subscriptions should be made in onCreate. Can you move them there and see if that helps?

**Comment by krage** [comment]
For tidiness and preventing misuse of the viewbinding it's not available in some of these fragments outside of `onCreateView` so moving all subscriptions up to `onCreate` would take some restructuring. The easier bandaid fix for me is probably tacking on an extra observer to directly call `dispose()` on each of these subscriptions at `viewLifecycle`'s destroyed state - they already each need an edit to remove the old lifecycle arg anyways.

Regardless of potential workarounds though shouldn't subscriptions made with `viewLifecycle` still be disposed when view lifecycle reaches destroyed? The doc comment linked above for `subscriptionLifecycleOwner` in `MavericksView` still suggests that's the case:

> Subscriptions made in or after `onCreateView` should use the fragment's _view's_ lifecycle owner so that they are cleared in `onDestroyView`.

**Comment by krage** [comment]
Added a test subscription started in `onCreate` (should be subscribing with fragment lifecycle), logged there and in fragment `onDestroy`:
```
onCreate ⇒ 1 subscriptions started in onCreate, isDisposed: [false]
onDestroy ⇒ 1 subscriptions started in onCreate, isDisposed: [false]
```
Also logged the state of the previous collection started in `onCreateView` (with view lifecycle) to fragment's `onDestroy` and none of them are disposed at that point either:
```
onCreateView ⇒ 1 subscriptions started in onCreateView, isDisposed: [false]
onDestroyView ⇒ 1 subscriptions started in onCreateView, isDisposed: [false]
onCreateView ⇒ 2 subscriptions started in onCreateView, isDisposed: [false, false]
onDestroyView ⇒ 2 subscriptions started in onCreateView, isDisposed: [false, false]
onCreateView ⇒ 3 subscriptions started in onCreateView, isDisposed: [false, false, false]
onDestroyView ⇒ 3 subscriptions started in onCreateView, isDisposed: [false, false, false]
onDestroy ⇒ 3 subscriptions started in onCreateView, isDisposed: [false, false, false]
```
No obvious adverse effects from subscriptions lingering though `onDestroy` but there's also no new state being produced in the viewmodel... maybe subscriptions are eventually still ending by their sources completing as the fragment-scoped viewmodel is cleared?

**Comment by krage** [comment]
Another round switching instead to jobs created with `onAsync` and tracking their `isActive`.
For fragment lifecycle jobs started in `onCreate` looks good:
```
onCreate ⇒ 1 jobs created in onCreate, isActive: [true]
onDestroy ⇒ 1 jobs created in onCreate, isActive: [false]
```
But for view lifecycle jobs started in `onCreateView`:
```
onCreateView ⇒ 1 jobs created in onCreateView, isActive: [true]
onDestroyView ⇒ 1 jobs created in onCreateView, isActive: [true]
onCreateView ⇒ 2 jobs created in onCreateView, isActive: [true, true]
onDestroyView ⇒ 2 jobs created in onCreateView, isActive: [true, true]
onCreateView ⇒ 3 jobs created in onCreateView, isActive: [true, true, true]
onDestroyView ⇒ 3 jobs created in onCreateView, isActive: [true, true, true]
onDestroy ⇒ 3 jobs created in onCreateView, isActive: [false, false, false]
```
no longer active in `onDestroy` is an improvement vs the disposables but I still would've expected these to have ended earlier by `onDestroyView`.

**Comment by gpeal** [comment]
@krage Mavericks handles all of that for you :) You do your subscription in onCreate but it will only ever be invoked with the view is started so you can freely using bindings in it.

**Comment by krage** [comment]
@gpeal Whether or not that's the case [`MavericksView` docs](https://github.com/airbnb/mavericks/blob/891d640979043af8c2cbe5004d26e2ad43dedb0d/mvrx/src/main/kotlin/com/airbnb/mvrx/MavericksView.kt#L58-L73) still say subscriptions made in or after `onCreateView` should use `viewLifecycle` and will be cleared in `onDestroyView`:
```kotlin
    /**
     * The [LifecycleOwner] to use when making new subscriptions. You may want to return different owners depending
     * on what state your [MavericksView] is in. For fragments, subscriptions made in `onCreate` should use
     * the fragment's lifecycle owner so that the subscriptions are cleared in `onDestroy`. Subscriptions made in or after
     * `onCreateView` should use the fragment's _view's_ lifecycle owner so that they are cleared in `onDestroyView`.
     *
     * For example, if you are using a fragment as a [MavericksView] the proper implementation is:
     * ```
     *     override val subscriptionLifecycleOwner: LifecycleOwner
     *        get() = this.viewLifecycleOwnerLiveData.value ?: this
     * ```
     *
     * By default [subscriptionLifecycleOwner] is the same as the MvRxView's standard lifecycle owner.
     */
    val subscriptionLifecycleOwner: LifecycleOwner
        get() = (this as? Fragment)?.viewLifecycleOwnerLiveData?.value ?: this
```

**Comment by gpeal** [comment]
@krage Yes, this is what ensures that the callback only happens when your view is started which is why it's safe to use bindings in your callback. However, it is still advised to make the subscription in onCreate.

**Comment by krage** [comment]
@gpeal I feel like you're still not hearing the issue here. Previous behavior and current documentation both say that subscriptions made in/after `onCreateView` should use the view's lifecycle. **Currently they do not**.

After more investigation the main problem is that `viewLifecycleOwnerLiveData.value` is still null in `onCreateView` so default `subscriptionLifecycleOwner` implementation still uses `Fragment` lifecycle there. A possible fix to support using view lifecycle in the way it's described in the documentation is replacing/overriding `subscriptionLifecycleOwner` with:

```kotlin
val subscriptionLifecycleOwner: LifecycleOwner
    get() = try {
        (this as? Fragment)?.viewLifecycleOwner ?: this
    } catch(e: IllegalStateException) {
        this
    }
```
I feel like it's not great to have to use the exception as a signal here but with the change in Mavericks to not directly accept a lifecycle owner at the point of subscription this seems like the available alternative.

There's also a secondary kind of cosmetic issue where the disposable wrapper added to jobs in [`MvRxView`](https://github.com/airbnb/mavericks/blob/891d640979043af8c2cbe5004d26e2ad43dedb0d/mvrx-rxjava2/src/main/kotlin/com/airbnb/mvrx/MvRxView.kt#L214-L216) doesn't get marked disposed when the internal job completes. Here's a possible quick fix that works. It would probably be improved with a more direct implementation of `Disposable` that was job-aware so that `isDisposed` could be derived directly from `!isActive` and the job being cancelled wouldn't need to call `dispose()` thus re-triggering the action and calling `cancel()` on that already complete job:

```kotlin
private fun Job.toDisposable() = Disposables.fromAction {
    cancel()
}.apply { this@toDisposable.invokeOnCompletion { dispose() } }
```


I added similar logging (with better formatting) to the `hellohilt` sample app. To keep changes minimal since `HelloHiltState` has no `Async` fields I used `onEach`/`selectSubscribe` instead of `onAsync`/`asyncSubscribe`.  `Disposable`s are logged as "subscriptions" with subscribed status from `!isDisposed` so they're directly comparable to `Job.isActive`.

Before the above fixes:
```
onCreate      ⇒ 1 jobs started in onCreate,                isActive: [true]
onCreate      ⇒ 1 subscriptions started in onCreate,     subscribed: [true]
onCreateView  ⇒ 1 jobs started in onCreateView,            isActive: [true]
onCreateView  ⇒ 1 subscriptions started in onCreateView, subscribed: [true]
onDestroyView ⇒ 1 jobs started in onCreateView,            isActive: [true]
onDestroyView ⇒ 1 subscriptions started in onCreateView, subscribed: [true]
onCreateView  ⇒ 2 jobs started in onCreateView,            isActive: [true, true]
onCreateView  ⇒ 2 subscriptions started in onCreateView, subscribed: [true, true]
onDestroyView ⇒ 2 jobs started in onCreateView,            isActive: [true, true]
onDestroyView ⇒ 2 subscriptions started in onCreateView, subscribed: [true, true]
onCreateView  ⇒ 3 jobs started in onCreateView,            isActive: [true, true, true]
onCreateView  ⇒ 3 subscriptions started in onCreateView, subscribed: [true, true, true]
onDestroyView ⇒ 3 jobs started in onCreateView,            isActive: [true, true, true]
onDestroyView ⇒ 3 subscriptions started in onCreateView, subscribed: [true, true, true]
onDestroy     ⇒ 3 jobs started in onCreateView,            isActive: [false, false, false]
onDestroy     ⇒ 3 subscriptions started in onCreateView, subscribed: [true, true, true]
onDestroy     ⇒ 1 jobs started in onCreate,                isActive: [false]
onDestroy     ⇒ 1 subscriptions started in onCreate,     subscribed: [true]
```
and after these two fixes:
```
onCreate      ⇒ 1 jobs started in onCreate,                isActive: [true]
onCreate      ⇒ 1 subscriptions started in onCreate,     subscribed: [true]
onCreateView  ⇒ 1 jobs started in onCreateView,            isActive: [true]
onCreateView  ⇒ 1 subscriptions started in onCreateView, subscribed: [true]
onDestroyView ⇒ 1 jobs started in onCreateView,            isActive: [false]
onDestroyView ⇒ 1 subscriptions started in onCreateView, subscribed: [false]
onCreateView  ⇒ 2 jobs started in onCreateView,            isActive: [false, true]
onCreateView  ⇒ 2 subscriptions started in onCreateView, subscribed: [false, true]
onDestroyView ⇒ 2 jobs started in onCreateView,            isActive: [false, false]
onDestroyView ⇒ 2 subscriptions started in onCreateView, subscribed: [false, false]
onCreateView  ⇒ 3 jobs started in onCreateView,            isActive: [false, false, true]
onCreateView  ⇒ 3 subscriptions started in onCreateView, subscribed: [false, false, true]
onDestroyView ⇒ 3 jobs started in onCreateView,            isActive: [false, false, false]
onDestroyView ⇒ 3 subscriptions started in onCreateView, subscribed: [false, false, false]
onDestroy     ⇒ 3 jobs started in onCreateView,            isActive: [false, false, false]
onDestroy     ⇒ 3 subscriptions started in onCreateView, subscribed: [false, false, false]
onDestroy     ⇒ 1 jobs started in onCreate,                isActive: [false]
onDestroy     ⇒ 1 subscriptions started in onCreate,     subscribed: [false]
```
Not ideal fixes but made with a relatively light touch. The subscription lifecycle results are now what I'd expect. Thoughts?

**Comment by elihart** [comment]
@krage yes, you're right that subscribing in onCreateView is supposed to be supported, and result in the subscription being canceled in onDestroyView. We added that support explicitly with https://github.com/airbnb/mavericks/pull/210

The code you pointed to looks like it should still be working
```
    override val subscriptionLifecycleOwner: LifecycleOwner
        get() = this.viewLifecycleOwnerLiveData.value ?: this
```

and it is a bit alarming if it doesn't. I don't know that that implementation would have changed from mvrx 1.x so I'm curious if the upgrade to 2.x is actually related (besides that before you could make it work with an manual lifecycle override). We rely on this fairly often at airbnb for subscribing in onViewCreated, and haven't had problems.

Looking at `getViewLifecycleOwnerLiveData` the javadoc says `This will be set to the new {@link LifecycleOwner} after {@link #onCreateView} returns a non-null View and will set to null after {@link #onDestroyView()}.`

Whereas `getViewLifecycleOwner` javadoc clearly says it is accessible within onCreateView.

So I think that explains the behavior you are seeing (and also why we haven't had a problem at airbnb since we use onViewCreated). One option is to change documentation to say that view lifecycle subscriptions should only be done in onViewCreated, but I think that is a bit confusing and error prone so using your try/catch approach does seem like the best thing to do.

As far as the Disposable not being disposed, that seems like a good catch and a reasonable fix - I don't have a strong opinion on it.

**Comment by krage** [comment]
Yeah that's the distinction I recognized as well - the existing implementation would work in `onViewCreated` but earlier in `onCreateView` even though the view lifecycle itself is available the livedata's value is null until the return so it does the wrong thing.

As described in my upgrade from 1.x I was passing in an explicit `LifecycleOwner` to every subscribe call made in fragments so I provided `viewLifecycleOwner` directly there. Upon review it looks like those [variations of subscribe methods](https://github.com/airbnb/mavericks/blob/0fbe364f789ab68920707a44b8e9d590bef7f974/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxViewModel.kt#L304-L311) in `BaseMvRxViewModel` that include that lifecycle owner as first arg were marked `@RestrictTo(RestrictTo.Scope.LIBRARY)` at least in `1.5.1` so I'm not sure how I ended up using them... maybe they weren't marked restricted in some prior version so they popped up as options in Android Studio autocomplete? In any case that explains why it worked for me in `1.x` - I was bypassing the [old implementation](https://github.com/airbnb/mavericks/blob/0fbe364f789ab68920707a44b8e9d590bef7f974/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxFragment.kt#L23-L28) of `subscriptionLifecycleOwner` in `BaseMvRxFragment` which does appear equivalent to the one currently in `MavericksView` and would have the same issue.

**Comment by krage** [comment]
Just had a quick try deleting those `viewLifecycleOwner` overrides made in `onCreateView` in my old build using `1.5.1` and it definitely fails in the same way without them.

**Comment by krage** [comment]
Here's a more complete `Disposable` wrapper for `Job` adapted from `ReferenceDisposable` to avoid the unnecessary re-cancel:

```kotlin
private class JobDisposable(job: Job) : AtomicReference<Job>(job), Disposable {
    init {
        job.invokeOnCompletion { set(null) }
    }

    override fun dispose() {
        getAndSet(null)?.cancel()
    }

    override fun isDisposed(): Boolean = get()?.isActive?.not() ?: true
}

private fun Job.toDisposable(): Disposable = JobDisposable(this)
```

Should I put this and the try/catch view lifecycle change in a PR (or two)?

**Comment by elihart** [comment]
@krage If you could just bundle those in the same PR we'd appreciate the contribution!
