### ISSUE TITLE
Recompile new compose alpha using beta07

### ISSUE THREAD

**Issue by inktomi** [airbnb/mavericks#548]
There are some changes in the latest Compose beta (version beta07) that require libraries to be recompiled against this version. Not doing so makes them incompatible, unfortunately.  This causes a runtime exception which will prevent the application from launching. 

https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.0.0-beta07

**Comment by gpeal** [comment]
I think this is related to navigation-compose not mavericks but I put up https://github.com/airbnb/mavericks/pull/549 anyway

**Comment by inktomi** [comment]
Thank you! I was seeing the runtime error from Compose at launch. I look forward to trying the updated alpha.

**Comment by inktomi** [comment]
This is solved by the recent release including #549
