### ISSUE TITLE
support kmm?

### ISSUE THREAD

**Issue by lwj1994** [airbnb/mavericks#558]
Is it possible to consider applying mvrx to [kmm](https://kotlinlang.org/docs/mobile/home.html)? Not just for Android。

**Comment by iadcialim** [comment]
Hi. Just to be clear, does this library support multiplatform now?

**Comment by elihart** [comment]
Not really. The [mvrx-common](https://github.com/airbnb/mavericks/tree/main/mvrx-common) module is a pure jvm module with no android dependencies, but there hasn't been any work done to expand to supporting other platforms.

**Comment by artillerymans** [comment]
The official documentation describes the lifecycle (*) library as having multi-platform support, so would it normally be possible to use this library directly on multiple platforms?

按照官方的文档描述 lifecycle (*) 库已经支持多平台，正常来说这个库是否就可以直接在多平台上使用？

https://developer.android.com/kotlin/multiplatform
