### ISSUE TITLE
Question about invalidate & onAsync

### ISSUE THREAD

**Issue by wooooooak** [airbnb/mavericks#561]
## 1. invalidate 
The invalidate function is not called in the activity, and it is called only in the Fragment. For what reason? Since Activity can implement MavericksView, invalidate implementation is forced. But it's confusing because it's not actually called.

## 2.onAsync
Is there any reason not to accept `onLoading` as parameters of the onAsync function?

**Comment by gpeal** [comment]
1) Activities are no longer meant for handling UIs. They should just be hosts for your Fragments, composables, or whatever else you're using within your app. For that reason, the activity implementation is as simple as possible. If you really need it, you can wire it up yourself with:
```kotlin
onCreate(...) {
   super.onCreate(...)
    viewModel.onEach { postInvalidate() }
}
```

2) At that point, you should probably just use onEach like:
```
viewModel.onEach(MyState::myProp) { myProp ->
    when (myProp) {
        is Loading -> ...
        is Succss -> ...
        ...
    }
}
```
