### ISSUE TITLE
Koltin 1.5.21 (for Compose 1.0.1)

### ISSUE THREAD

**Issue by inktomi** [airbnb/mavericks#569]
I've love to help with getting the project onto Compose 1.0.1 rather than on the alpha releases. This would entail also updating to Kotlin 1.5.21 (.30 isn't supported by Compose 1.0.1..).

Would this be something that you'd be open to some help on? I think it'd be a matter of updating the dependency and then fixing any detekt issues that come up, correct? 

I've attempted this locally, and at least running `:mvrx:detekt` didn't report any errors, so if that's the correct command it seems like a straightforward upgrade.

**Comment by elihart** [comment]
sure, help updating dependencies is always appreciated. You can run detekt for the whole project with `./gradlew detekt`

**Comment by inktomi** [comment]
Thank you, I'll try to get that up Monday or early next week. Thank you!

Matt

**Comment by kaushalyap** [comment]
@elihart Is Compose support still experimental?

**Comment by elihart** [comment]
yes, in that it is being used but the api's may change
