### ISSUE TITLE
Passing an argument in state for compose.

### ISSUE THREAD

**Issue by DikarevPavel** [airbnb/mavericks#573]
Hi all. At the moment, when navigating from FirstScreen to SecondScreen, 
there is no way to directly pass arguments to mavericksViewModel() or retrieve an argument from the navigation. 
And in order for the viewModel to receive arguments, you need to pass them through "intent.putExtra (args)", 
this is if the navigation is in the MainActivity, and if the navigation is outside the MainActivity, 
then you will have to pass the activity to all navigation in order to use the "intent. putExtra (args) ".
For example:

```
data class TestArg(
    val count: Int = 0,
) : Serializable

data class ExampleState(
    val count: Int = 0,
) : MavericksState {
    constructor(args: TestArg): this(count = args.count)
}

class ExampleViewModel(initialState: ExampleState) : MavericksViewModel<ExampleState>(initialState) {

}

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            CounterScreenNavHost(intent)
        }
    }
}


@Composable
fun CounterScreenNavHost(intent: Intent) {
    val navController = rememberNavController()
    NavHost(navController, startDestination = "firstScreen") {
        composable("firstScreen") {
            FirstScreen {
                navController.navigate("secondScreen")
            }
        }
        composable("secondScreen") { stackEntry ->
            val testArg = TestArg(2)
            intent.putExtra(KEY_ARG, testArg) // problem when we have many screens with other args, because its one activity.
            SecondScreen {
                navController.popBackStack()
            }
        }
    }
}

@Composable
fun FirstScreen(navTo: () -> Unit) {
    HcmScaffold(
        content = {
            Box(
                contentAlignment = Alignment.Center,
                modifier = Modifier.padding(it).clickable {
                    navTo()
                }
            ) {
                Text("Example ")
            }
        }
    )
}

@Composable
fun SecondScreen(navBack: () -> Unit) {
    val viewModel = mavericksViewModel<ExampleViewModel, ExampleState>()
    val state = viewModel.collectAsState().value
    HcmScaffold(
        content = {
            Box(
                contentAlignment = Alignment.Center,
                modifier = Modifier.padding(it).clickable {
                    navBack()
                }
            ) {
                Text("Example ${state.count}")
            }
        }
    )
}
```
I believe that in order to solve this problem, we need the ability to pass an optional parameter 
to mavericksViewModel() or retrieve directly from the navigation.
For example: 

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            CounterScreenNavHost()
        }
    }
}


@Composable
fun CounterScreenNavHost() {
    val navController = rememberNavController()
    NavHost(navController, startDestination = "firstScreen") {
        composable("firstScreen") {
            FirstScreen {
                navController.navigate("secondScreen")
            }
        }
        composable("secondScreen") { stackEntry ->
            val testArg = TestArg(2)
            SecondScreen(
                navBack = {
                    navController.popBackStack()
                },
                testArg = testArg,
            )
        }
    }
}

@Composable
fun FirstScreen(navTo: () -> Unit) {
    HcmScaffold(
        content = {
            Box(
                contentAlignment = Alignment.Center,
                modifier = Modifier.padding(it).clickable {
                    navTo()
                }
            ) {
                Text("Example ")
            }
        }
    )
}

@Composable
fun SecondScreen(navBack: () -> Unit, testArg: TestArg) {
    val viewModel = mavericksViewModel<ExampleViewModel, ExampleState>(testArg) // resolve problem, one set args for each screen
    val state = viewModel.collectAsState().value
    HcmScaffold(
        content = {
            Box(
                contentAlignment = Alignment.Center,
                modifier = Modifier.padding(it).clickable {
                    navBack()
                }
            ) {
                Text("Example ${state.count}")
            }
        }
    )
}
```

**Comment by vladimirfx** [comment]
We need this too - some Compose-native way to navigate with arguments. A possible way to is some sort of initial state factory (with access to navigation context). In such a factory, we can access Jetpack Navigation arguments and pass them to the initial state.

**Comment by elihart** [comment]
It sounds like you should be using the `keyFactory` parameter in mavericksViewModel in order to specify that you want a different viewmodel instance per screen. That solves the problem of separating the viewmodels to have different arguments.

As far as providing the arguments, I think it would be pretty trivial to add an optional param to mavericksViewModel to provide initial arguments, like `noinline argsFactory: (() -> Any?)? = null`

**Comment by jakoss** [comment]
@elihart Should I pass args created by this factory as `args` in `FragmentViewModelContext` and `ActivityViewModelContext`? If yes - what should have priority, arguments from `Fragment.arguments`/`Activity.intent` or that passed manually via factory?

**Comment by jakoss** [comment]
@elihart Implementing that i found another bug. When i tried to pass argument to fragment and then get the viewModel in composable the argument never gets passed. The reason is simple:

The `scope: LifecycleOwner = LocalLifecycleOwner.current` will return `FragmentViewLifecycleOwner` for fragment. So the code:
```kotlin
is Fragment -> {
    val args = scope.arguments?.get(Mavericks.KEY_ARG)
    FragmentViewModelContext(activity, args, scope)
}
```
Will never be called. `FragmentViewLifecycleOwner` have fragment property, but the whole class is private in `androidx.fragment` i'm not sure how to access fragment from composable. I'm not sure if that's even possible...

**Comment by elihart** [comment]
@jakoss yes, I believe the args passed manually through `fun mavericksViewModel` should go into ActivityViewModelContext/FragmentViewModelContext and should have precedence over frament/activity arguments

**Comment by elihart** [comment]
good catch on the Fragment bug. As of androidx fragment library 1.3.4 I see `FragmentViewLifecycleOwner` as being public though, which should be possible to check for. are you sure it's private?

**Comment by jakoss** [comment]
That's weird, i couldn't find the type using Android Studio autocomplete, and i checked in sources that the class is indeed package private: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment/src/main/java/androidx/fragment/app/FragmentViewLifecycleOwner.java;l=37?q=FragmentViewLifecycleOwner&sq=

**Comment by elihart** [comment]
here's an idea - use the composition local `LocalView` to get the parent view (if one exists), and then use `FragmentManager.findFragment(view)` to get the associated Fragment. that seems like it should work

**Comment by jakoss** [comment]
I'll check that!

**Comment by elihart** [comment]
sounds great, thanks! yes, catching the exception should be fine, we use that pattern elsewhere in mavericks when working with androidx
