### ISSUE TITLE
How to unit test suspend-execute?

### ISSUE THREAD

**Issue by fivelayer** [airbnb/mavericks#575]
Hello.
I am incrementing the counter using suspend-execute.
```kotlin
data class MyViewState(
    val count: Int = 0,
    val countAsync: Async<Int> = Uninitialized
) : MavericksState
...
// in ViewModel
fun asyncIncrementCount() {
    withState {
        suspend {
            delay(1000)
            it.count + 1
        }.execute {
            if (it is Success) {
                copy(countAsync = it, count = it())
            } else {
                copy(countAsync = it)
            }
        }
    }
}
```

Then I'm trying to unit test this function now, but I don't know the best way. 
Because execute is called multiple times, and the time when it is called is out of my control, I don't know what to do. I want to test the state when it is Loading and the state when it is Success, but how should I do it? **Of course, in production code, the delay is replaced by the network speed, so you won't know the exact time.**

My stupid test code. Of course, It is failed.
```kotlin
@ExperimentalCoroutinesApi
@Test
fun async_test() {
    myViewModel.asyncIncrementCount()
    withState(myViewModel) {
        println("count: ${it.count}, countAsync: ${it.countAsync}")
        assertEquals(it.count, 0) // passed. because async is Loading, and count is 0.
    }

    withState(myViewModel) {
        println("count: ${it.count}, countAsync: ${it.countAsync}")
        assertEquals(it.count, 1) // fail!!!!!!!!!
    }
}
```

**Comment by gpeal** [comment]
@fivelayer add the `mavericks-testing` artifact and use the test rule like this
https://github.com/airbnb/mavericks/blob/master/hellodagger/src/test/java/com/airbnb/mvrx/hellodagger/HelloDaggerViewModelTest.kt#L16

**Comment by fivelayer** [comment]
> @fivelayer add the `mavericks-testing` artifact and use the test rule like this
> https://github.com/airbnb/mavericks/blob/master/hellodagger/src/test/java/com/airbnb/mvrx/hellodagger/HelloDaggerViewModelTest.kt#L16

@gpeal 
I looked at the code, but inside the execute function, loading is setState initially, so the test result is not FAILED?
In my code, it.countAsync in withState is Loading, so I can't test the value when Success.

What should I do?

**Comment by fivelayer** [comment]
> @fivelayer add the `mavericks-testing` artifact and use the test rule like this
> https://github.com/airbnb/mavericks/blob/master/hellodagger/src/test/java/com/airbnb/mvrx/hellodagger/HelloDaggerViewModelTest.kt#L16

I Did. But i got error.
```
You must initialize Mavericks. Add Mavericks.initialize(...) to your Application.onCreate().
java.lang.IllegalStateException: You must initialize Mavericks. Add Mavericks.initialize(...) to your Application.onCreate().
```

Here is my code
```kotlin
internal class ExampleUnitTest {

    @get:Rule
    val mvrxTestRule = MvRxTestRule()

    private val initState = MyViewState()
    private var myViewModel = MyViewModel(initState)
    

    @ExperimentalCoroutinesApi
    @Test
    fun async_test() {
        myViewModel.asyncIncrementCount()
        withState(myViewModel) {
            println("count: ${it.count}, countAsync: ${it.countAsync}")
            assertEquals(it.count, 0)
        }
    }
}
```

**Comment by alvindizon** [comment]
Running into this intermittently, albeit with Rx. Have used all the correct unit testing artifacts and used the correct JUnit 4 rules. But sometimes, unit tests fail because Async is still Loading.
