### ISSUE TITLE
Async, Compose and Unidirectional Data Flow

### ISSUE THREAD

**Issue by franciscoaleixo** [airbnb/mavericks#579]
I've been using Async for a while and I enjoy it quite a bit. However, I'm curious on how you generally structure your state when you have a state property that not only is it loaded async, but can also be changed by the user afterwards (and let's say we are using Compose).

To be clearer, let's say we have a FiltersScreen. It has different filters that are saved to db, so when we launch the screen, we load the last saved filters from db -- we can generally represent this with something like `Async<Filters>`. So then, our compose function observes this Async, and on success we just set its values. But how do we represent the changed state when the user interacts with the filters? I see three basic ways:

- Since `Async<Filters>` already exists, we could theoretically simply emit a new `Async.Success(Filters(...))` everytime the user changes the filters. I don't think this is a very good approach, because we're changing the initial purpose of Async itself. It's supposed to represent an asynchronous operation, but now it is being used to change state according to user input.
- We could have a new state property with Filters, but then it would mean our state kind of has two repeated state properties --` Async<Filters>` and `Filters`, although one is for loading the saved filters and the other for user interactions. Furthermore, then what is the actual filters we should use to set our UI? Should we use the Async<Filters> or Filters? It doesn't seem very clear, even if from a readability standpoint. I guess we would just use `Async<Filters> `to check if it is loading, success or fail, and `Filters` for the actual value.
- We don't use Async at all, and just use `Filters`. This is fine and works great, but we lose the benefit of our Async when we are loading the initial values or something goes wrong.

If I had to pick, I would probably pick the 2nd one, but how do you handle these cases? Is there a better way? Thanks.

**Comment by gpeal** [comment]
I might represent it more like the first, actually:
```kotlin
data class MyState(
  val filter: Async<Filters>
) : MavericksState

class MyViewModel(
  initialState: MyState,
  filtersDao: FiltersDao,
) : MavericksViewModel<MyState>(initialState) {
  init {
    suspend {
      filtersDao.getFilters()
    }.execute { copy(filters = it) }
  }

  fun setFilters(filters: List<Filters>) {
    setState { copy(filters = Success(filters)) }
    viewModelScope.launch {
      filtersDao.saveFilters(filters)
    }
  }
}
```

**Comment by franciscoaleixo** [comment]
@gpeal Thanks for the snippet! I think that is probably the clearer option. I guess my initial criticisms were that it felt a bit like abandoning the purpose of Async. The success value no longer is necessarily the result of an asynchronous operation. At the end of the day, it's just semantics and pragmatically speaking that is probably the better option. Thanks!
