### ISSUE TITLE
Move from `master` to `main` or similar for the default branch

### ISSUE THREAD

**Issue by inktomi** [airbnb/mavericks#587]
The default for new projects on GitHub is a `main` branch, rather than a `master` branch. Though this seems like a simple enough difference, for some `master` can be a racially loaded term. In keeping with [AirBnB's pledge to support inclusiveness](https://news.airbnb.com/an-update-on-our-efforts-to-support-racial-justice/) would you be willing to migrate Mavericks from `master` to something else for the default branch?

**Comment by elihart** [comment]
Yes, this is something we want to do for all our open source projects, just haven't gotten around to it.

If anyone would like to contribute a PR to do so it would be much appreciated :)

**Comment by inktomi** [comment]
I'm happy to open a PR. The changes don't seem too major - I don't see any mention of the branch in Travis/etc so it seems like you may need to tweak the config a bit on that end unless it just picks up the default from GitHub.
