### ISSUE TITLE
2.5.0 release does not include compose

### ISSUE THREAD

**Issue by jakoss** [airbnb/mavericks#593]
@elihart I'm glad we have 2.5.0 release, but since most of release notes cover compose integration then we probably should have a `mavericks-compose` artifact release as well :)

**Comment by elihart** [comment]
hm, right. I forgot the compose artifact is on its own alpha versioning scheme https://github.com/airbnb/mavericks/blob/main/mvrx-compose/gradle.properties

**Comment by jakoss** [comment]
Yes, that's another question if you still think it's not stable. There's this pending bug with passing argument to viewmodel which is pretty important IMO: https://github.com/airbnb/mavericks/issues/573

**Comment by jakoss** [comment]
@elihart is there any news about compose artifact release?

**Comment by elihart** [comment]
I will try to make a release for it this week sometime

**Comment by elihart** [comment]
@jakoss are you interested in making a contribution to enable https://github.com/airbnb/mavericks/issues/573? I responded there with what I think is a fairly easy solution

**Comment by jakoss** [comment]
@elihart here you go, I hope it's proper solution https://github.com/airbnb/mavericks/pull/595
