### ISSUE TITLE
ComponentActivity.viewModel() requires opt-in

### ISSUE THREAD

**Issue by vulpeszerda** [airbnb/mavericks#597]
I'm using Mavericks library not only for Fragment, Activity as well.
When I use Mavericks `ViewModel` in Activity, I use below.
```kotlin
inline fun <T, reified VM : MavericksViewModel<S>, reified S : MavericksState> T.viewModel(
    viewModelClass: KClass<VM> = VM::class,
    crossinline keyFactory: () -> String = { viewModelClass.java.name }
)
```

However, whenever I use this, IDE complains `This is internal Mavericks API. It is not intended for external use`. I think this is because `T.viewModel` method declared as `inline func` and it uses `lifecycleAwareLazy`(which marked as `@InternalMavericksApi`) internally. 

Is this `T.viewModel` method REALLY intended for internal use? 
If not, then this `This is internal Mavericks API...` warning should be removed.

BTW, 
I have been big fan of this library since few years ago.
Always thanks for great efforts :)

**Comment by elihart** [comment]
Hey, yes you are right. This function is intended to be used, and it seems the `lifecycleAwareLazy` is triggering the issue. I _think_ that if we explicitly make the return type `Lazy` then the error will go away since `lifecycleAwareLazy` will then no longer leak

**Comment by vulpeszerda** [comment]
Thank you for accepting!! 🙂
