### ISSUE TITLE
Extend the target of @ViewModelKey

### ISSUE THREAD

**Issue by jakoss** [airbnb/mavericks#609]
I'm trying out the new hilt artifact, and i have one issue that is conflicting in my use case. I'm using `hilt-binder` library (https://github.com/mars885/hilt-binder) to automate generating the boilerplate for assisted factory. So instead of doing:
```kotlin
@AssistedFactory
    interface Factory : AssistedViewModelFactory<TestViewModel, TestState> {
        override fun create(state: TestState): TestViewModel
    }

// then manually register the factory
@Module
@InstallIn(MavericksViewModelComponent::class)
interface TestViewModelModule {

    @Binds
    @IntoMap
    @ViewModelKey(TestViewModel::class)
    fun testViewModelFactory(factory: TestViewModel.Factory): AssistedViewModelFactory<*, *>
}
```

I can just do:
```kotlin
@BindType(
        installIn = BindType.Component.CUSTOM,
        customComponent = MavericksViewModelComponent::class,
        to = AssistedViewModelFactory::class,
        contributesTo = BindType.Collection.MAP
    )
    @ViewModelKey(TestViewModel::class)
    @AssistedFactory
    interface Factory : AssistedViewModelFactory<TestViewModel, TestState> {
        override fun create(state: TestState): TestViewModel
    }
```

For me it's much simpler to keep everything in ViewModel, so i don't have to jump to module to register every single view model there. This is working fine, but not with the new artifact. The only thing that's keeping me from using it is that `@Target` for `ViewModelKey` is set to `@Target(AnnotationTarget.FUNCTION)`. I'm locally using `@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CLASS)` which allows me to use it on the `interface` directly.

So my question is - are you open to add new annotation target to `ViewModelKey`? @itsandreramon You were the pushing force for the artifact, what do you thing about that?

**Comment by itsandreramon** [comment]
Does not seem like a big deal to me, but what I'm unsure about is supporting different 3rd party libraries. You could, however, easily add your own ViewModelKey and use it on your Factory and it should work just fine. You would still reduce most of the boilerplate when using the new -hilt artifact.

```kotlin
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CLASS)
@MapKey
annotation class CustomViewModelKey(val value: KClass<out MavericksViewModel<*>>)
```

**Comment by jakoss** [comment]
Oh yea, i haven't noticed that the `@ViewModelKey` is not really used anywhere but the map registration. So using custom key is fine for me as well

**Comment by elihart** [comment]
Adding the target doesn't seem like a problem to me either, but since this is specifically for another library interop (which is likely not common) and if you can work around it with your own key, but it's maybe best to not make the change to mavericks

**Comment by jakoss** [comment]
Yes, i agree. I'll those the thread
