### ISSUE TITLE
How do I use Mavericks in Activity？

### ISSUE THREAD

**Issue by CxxyLucifer** [airbnb/mavericks#616]
`package com.airbnb.mvrx.sample

import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import com.airbnb.mvrx.MavericksState
import com.airbnb.mvrx.MavericksView
import com.airbnb.mvrx.sample.core.MvRxViewModel
import com.airbnb.mvrx.viewModel
import com.airbnb.mvrx.withState

data class ViewModelMainState(val name: String = "this is original name") : MavericksState {
}
class ViewModelMainModel(initialState: ViewModelMainState) : MvRxViewModel<ViewModelMainState>(initialState) {
    fun setName(nameNew: String) = setState { copy(name = nameNew) }
}
class MainActivity : AppCompatActivity(), MavericksView {
    private val viewModel: ViewModelMainModel by activityViewModel()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        viewModel.setName("this is new name")
    }
    override fun invalidate(): Unit =  withState(viewModel) { state ->
        Log.e("MainActivity", "MainActivity:${state.name}")
    }
}`

by activityViewModel() does not work ? what should i do ?

**Comment by gpeal** [comment]
activityViewModel() is designed to get an activity scoped view model from a Fragment. You want just `by viewModel()`
https://github.com/airbnb/mavericks/blob/main/mvrx/src/main/kotlin/com/airbnb/mvrx/MavericksExtensions.kt#L211

However, I recommend using Fragments. Putting UI directly inside of an Activity is no longer recommended in general for Android.

**Comment by longxuewei** [comment]
At present, our company's projects are developed based on Activity, and Fragment is used very little. How can I use this framework
