### ISSUE TITLE
State reducer getting called 6 times for MockableMavericks

### ISSUE THREAD

**Issue by safa007** [airbnb/mavericks#622]
My team recently discovered that using `MockableMavericks.initialize()` causes the state reducer to get called six times in debug mode, as opposed to the regular debug behavior of `Mavericks.initialize()` which calls all state reducers twice. 

Is this a bug or intended behavior?

**Comment by elihart** [comment]
this is intended

**Comment by elihart** [comment]
it gets called double for the debug checks, plus each of the state stores internally have the state reducer set on them to enable switching between state store types (synchronous vs asynchronous, etc)

Given reducers should be pure it should not create a behavior difference

**Comment by safa007** [comment]
Gotcha, makes sense. We have a couple instances where we use `if(it is Success)` inside of the execute to trigger certain functions once, but I think we need to move away from that. 
For `asyncSubscribe` is there a way to trigger certain actions only once, similar to the `asyncSubscribe` in the fragment that can use `uniqueOnly`?

**Comment by safa007** [comment]
Makes sense, thanks. Closing this out.
