### ISSUE TITLE
Link to FragmentViewBindingDelegate.kt broken

### ISSUE THREAD

**Issue by caseta** [airbnb/mavericks#624]
👋 

[On this page](https://airbnb.io/mavericks/#/view-binding), I clicked on the link for [FragmentViewBindingDelegate.kt](https://github.com/airbnb/mavericks/blob/release/2.0.0/sample/src/main/java/com/airbnb/mvrx/sample/utils/FragmentViewBindingDelegate.kt) and received a 404. Was hoping to add it to a side project 

Thanks

**Comment by gpeal** [comment]
Updated the docs to https://github.com/airbnb/mavericks/blob/main/view-binding-utils/src/main/java/com/airbnb/mvrx/viewbinding/FragmentViewBindingDelegate.kt
