### ISSUE TITLE
Handle view diffing in XML based views. 

### ISSUE THREAD

**Issue by Sardorbekcyber** [airbnb/mavericks#625]
Do you know any workaround to know diffing of view. In MVVM each view had its own state and rendering was appropritate to single change but when all screen is combined to single state it gets rendered on every state change. How this issue can be addressed?

I tried to use diff builder from MVI Kotlin by Ark Ivanov but there was no rendering in after navigating back.

**Comment by gpeal** [comment]
Setting a property on a view should be idempotent so that the actual `invalidate()` method should be very, very lightweight.
