### ISSUE TITLE
How to initiate multiple requests with uniform processing status

### ISSUE THREAD

**Issue by Sunyuwumengsheng** [airbnb/mavericks#627]
I have two requests A and B. When the page is initialized, I need to request both A and B, and then I need to request B separately.I do now, but think it's problematic.

  init {
       getBanner()
       getArticle(0)
   }

    fun getBanner() = withState { state ->
        if (state.bannerRequest is Loading) return@withState

        suspend {
            api.getBanner()

        }.execute {
            copy(
                banner = it()?.data ?: emptyList(),
                bannerRequest = it
            )
        }
    }

    fun getArticle(page: Int) = withState { state ->
            if (state.articleRequest is Loading) return@withState

            suspend {
                api.getArticle(page)
            }.execute {
                copy(
                    articles = it()?.data ?: Article(),
                    articleRequest = it
                )
            }
        }

**Comment by Sunyuwumengsheng** [comment]
sorry my english is not good
The effect I want is something like this
` suspend {
            zip(api.getBanner()， api.getArticle(page))
        }.execute {
            copy(
                bannerRequest= it.bannerRequest
                articleRequest = it.articleRequest 
            )
        }`

**Comment by gpeal** [comment]
Sounds like you got it working 😄
