### ISSUE TITLE
How to properly Unit test the State?

### ISSUE THREAD

**Issue by martymiller** [airbnb/mavericks#628]
I wrote some basic code (that most certainly doesn't compile) to reflect the problem I'm having.  Since classes like `ViewModelTest` are not publicly released in the SDK, do you see a fix for the following code that will make the test pass?

<img width="752" alt="Screen Shot 2022-04-28 at 12 22 24 PM" src="https://user-images.githubusercontent.com/3698882/165831158-fcc79534-9930-4fb5-804b-36effb0f7c03.png">

I should note that we are currently on an older version of MvRx (1.5.1)

@elihart

**Comment by gpeal** [comment]
The `MvRxTestRule` is for this
https://github.com/airbnb/mavericks/blob/e8a631a19fc1b044da3ddff358712e129dc487a6/hellodagger/src/test/java/com/airbnb/mvrx/hellodagger/HelloDaggerViewModelTest.kt#L16

**Comment by martymiller** [comment]
thanks @gpeal 

We actually have this line in our code as well. But I'm not sure what it does.  `mvrxRule` doesn't get referenced in the above code or ours.

**Comment by gpeal** [comment]
It's a junit test rule that sets a synchronous setState reducer before the test runs
