### ISSUE TITLE
need help.

### ISSUE THREAD

**Issue by xuexixuexijpg** [airbnb/mavericks#636]
Hello, I used this library as an exercise, I found a problem, when I return from the current `fragment `to the previous `fragment`, the scroll state of the previous `fragment `list is not saved, because the `MavericksViewModel `is not saved to the fragment status?
But using Google's `ViewModel `preserves the original scroll state. Is there any way or api to solve it? In addition, I did not use `epoxy `to build, because I practiced a **single activity** architecture, using `epoxy `in `fragment `to report adapter leaks and the memory seems to increase rapidly.
The currently used version of **navigation** and **viewmodel** is 2.5.0-rc01, the version of fragment is 1.5.0-rc01, and the version of **mavericks** is 2.7. Or is there anyone with the same problem? Is there any good solution? thanks

![Snipaste_2022-06-16_11-01-16](https://user-images.githubusercontent.com/57759182/173980807-a59f4826-0ba0-4683-97cd-7e314caf8d55.png)

**Comment by xuexixuexijpg** [comment]
![image](https://user-images.githubusercontent.com/57759182/174036932-8d3bcc0d-55eb-4943-832c-958b4b035852.png)

This is the code that uses Google's `ViewModel`, and returns the same data filled with `MavericksViewModel`

**Comment by gpeal** [comment]
Would https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter.StateRestorationPolicy#PREVENT_WHEN_EMPTY help?

**Comment by xuexixuexijpg** [comment]
![image](https://user-images.githubusercontent.com/57759182/174232915-4a56d1c2-8a56-45ca-b438-7054a155c0a6.png)

I still don't understand why Google's `ViewModel `can save the scroll position without setting this property. But it solved the problem, thank you very much~

**Comment by gpeal** [comment]
This has nothing to do with ViewModel, it has to do with the fact that RecyclerView has no items at the point in which it tries to restore scroll state.
