### ISSUE TITLE
How to adapt the hellodagger example for an Anvil multi-module project?

### ISSUE THREAD

**Issue by oheyadam** [airbnb/mavericks#638]
I might be slightly confused here, but I've been trying to figure this out for hours. The [DaggerMavericksViewModelFactory](https://github.com/airbnb/mavericks/blob/main/hellodagger/src/main/java/com/airbnb/mvrx/hellodagger/di/DaggerMavericksViewModelFactory.kt) access the appComponent to get `viewModelFactories()`, which means it has to live in the `:app` module, but that means that ViewModels in feature modules can't access the DaggerMavericksViewModelFactory class or [daggerMavericksViewModelFactory()](https://github.com/airbnb/mavericks/blob/ca0a719e1d546d012c367a5578fb67cda43e977f/hellodagger/src/main/java/com/airbnb/mvrx/hellodagger/di/DaggerMavericksViewModelFactory.kt#L25) function.

You can't move this class to the feature modules either because then it won't have access to the Application class to reference the `AppComponent`. How to make this work?

**Comment by gpeal** [comment]
At Tonal, this is what we have:
```
class DaggerMavericksViewModelFactory<VM : TonalViewModel<S>, S : MavericksState>(
    private val viewModelClass: Class<VM>,
) : MavericksViewModelFactory<VM, S> {
    override fun create(viewModelContext: ViewModelContext, state: S): VM {
        val bindings = when (viewModelContext) {
            is FragmentViewModelContext -> viewModelContext.fragment.bindings<LibUiBindings>()
            else -> viewModelContext.activity.bindings<LibUiBindings>()
        }
        val viewModelFactory = bindings.viewModelFactories()[viewModelClass] ?: error("Unable to find factory for ${viewModelClass.simpleName}")
        val castedViewModelFactory = viewModelFactory.cast<TonalViewModelFactory<VM, S>>()
        return castedViewModelFactory.create(state)
    }
}
```

where `Context/Fragment.bindings<T>` can get your Dagger component and cast it to type T

and
```
interface LibUiBindings {
    fun viewModelFactories(): Map<Class<out TonalViewModel<*>>, TonalViewModelFactory<*, *>>
}
```
which AppComponent implements.

We also use [Anvil](https://github.com/square/anvil) to further simplify our multi-module dagger setup but let me know if that helps.

**Comment by oheyadam** [comment]
Thank you very much. This was definitely helpful!
