### ISSUE TITLE
MockableMavericksView Memory Leak

### ISSUE THREAD

**Issue by safa007** [airbnb/mavericks#640]
My team has been noticing that any screen that implements `MockableMavericksView` has been leaking. So I replaced `MockableMavericksView` with `MavericksView` and the memory leaks stopped happening. 

All of the leaks look the exact same, pointing to `MockStateHolder.delegateInfoMap`. And the leaks are happening with all screens - even those that have no-op implementations of `provideMocks`.

Is this a known issue?

<img src="https://user-images.githubusercontent.com/26886907/178026036-942b4fa1-fcf8-43bd-b8bc-ce66b9b804c8.png" width="300">

**Comment by elihart** [comment]
Thanks for bringing this up.

Note first that this is the MockStateHolder used by MockableMavericks, which should only be used in dev, so no leaks will be in prod.

The MockStateHolder requires the mock to be cleared once you're done using it, via functions like clearAllMocks or clearMock. 

When calling `getMockVariants` the returned MockedViewProvider provides a MockedView which in turn as a lambda `cleanupMockState` that should be used to clean up the mock reference once the mock is done being used.

Depending on how you're using the mocks its up to your set up to clear the references properly. but if you don't its only a leak in dev builds.
