### ISSUE TITLE
Getting state from multiple flows with combine is causing recomposition

### ISSUE THREAD

**Issue by yveskalume** [airbnb/mavericks#662]
Here is my state

```kotlin
data class HomeViewState(
    val data : Async<HomeViewData> = Uninitialized
) : MavericksState

data class HomeViewData(
    val stores : List<Store> = emptyList(),
    val products : List<Product> = emptyList(),
    val groups : List<Group> = emptyList()
)
```

In the viewmodel I'm getting data from multiple usecases and putting their flows together with `combine` in order to produce one state of `HomeViewData()`

```kotlin
private fun getData() {
    viewModelScope.launch {
        val storesFlow = findTopStoreUseCase.invoke()
        val productsFlow = findAllProductsUseCase.invoke()
        val groupsFlow = findAllGroupUseCase.invoke()
      
        combine(storesFlow, productsFlow, groupsFlow) { stores, products, groups ->
            HomeViewData(stores = stores, products = products, groups = groups)
        }.execute {
            copy(data = it)
        }
    }
}
```

In the UI I'm just collecting the state as suggested in the doc

```kotlin
val dataState by viewModel.collectAsState(HomeViewState::data)

when (dataState) {
  Uninitialized -> {
      /**/
  }
  is Loading -> {
      /**/
  }
  is Success -> {
    /**/
  }
  is Fail -> {
   /**/
  }
}
```

But sometimes (usually if it's the first time I open the screen) I notice that there's more than necessary recompositions, and when i put a Log in the `execute` bloc I see that states are emitted twice like : 

```
Loading(value=null)
Loading(value=null)
Success()
Success()
```

I don't if it's because I'm using a real-time database (Firestore), but I'd like to know if there's a way to avoid this kind of behaviour.

Hopefully my explanation is clear, thanks !

**Comment by elihart** [comment]
maybe you just deep to update your combined flow to be deduped?

**Comment by yveskalume** [comment]
Isn't there a way to not emit the Loading state two consecutive times ?

**Comment by elihart** [comment]
the `execute` lambda is invoked multiple times in debug mode for validation purposes, but 1) that doesn't happen in production 2) it doesn't mean that a duplicate state is being emitted.
