### ISSUE TITLE
compare with mvc,mvp,mvvm

### ISSUE THREAD

**Issue by baneyue** [airbnb/mavericks#684]
This framework compares mvp, mvvm, and mvc, and finds that there is a slight delay in page display speed and button click feedback. May I ask how to use it to ensure excellent performance

**Comment by gpeal** [comment]
> slight delay in page display speed and button click feedback. May I ask how to use it to ensure excellent performance
Can you elaborate?

**Comment by baneyue** [comment]
that is my false
