### ISSUE TITLE
Ensure that your state properties properly implement hashCode.

### ISSUE THREAD

**Issue by artillerymans** [airbnb/mavericks#697]
What is the problem with this error and how should I check it

**Comment by artillerymans** [comment]
old ->
`@Keep
@Parcelize
data class ChatMsg(
    val text: String,
    val uuid: String = UUID.randomUUID().toString(),
    val type: Int = MsgType.SEND
): Parcelable`

new ->
`@Keep
@Parcelize
data class ChatMsg(
    val text: String,
    val type: Int = MsgType.SEND
): Parcelable`

If you remove the uuid, you won't get an error. Why?
My actual data is wrapped by List<ChatMsg> going through the

**Comment by gpeal** [comment]
Can you attach a sample app that reproduces this?

**Comment by artillerymans** [comment]
![image](https://github.com/airbnb/mavericks/assets/16060581/4db880e9-ded2-4cbd-ac1f-8ffaa290f837)
![image](https://github.com/airbnb/mavericks/assets/16060581/3b61239c-37ad-4959-9c79-c4fd03e23c73)
![image](https://github.com/airbnb/mavericks/assets/16060581/a9c5dc4d-e91d-4013-8b18-9efcd0634a90)

**Comment by gpeal** [comment]
The issue is that you're generating a random hashCode inside of your state class. You should initialize it either with a [state factory](https://airbnb.io/mavericks/#/factories?id=creating-a-state-class) in the companion object of your ViewModel or by calling setState in init. However, if you do the latter, you can't create a random variable inside of setState or else you'll wind up with the same error.
```
init {
	val initialUUID = UUID.randomUUID().toString()
    setState { copy(uuid = initialUUID) }
}
```

**Comment by artillerymans** [comment]
I changed the way I wrote it and the problem still exists, the weird thing is: the same code has the same data, it just throws exceptions some of the time and some of the time it doesn't

**Comment by artillerymans** [comment]
![image](https://github.com/airbnb/mavericks/assets/16060581/7a6febd8-70d5-4057-9c18-beef7713402e)
![image](https://github.com/airbnb/mavericks/assets/16060581/f283d2e3-da36-458a-9269-82bda122af30)
![image](https://github.com/airbnb/mavericks/assets/16060581/2556f23c-87d5-4ec0-9fac-eaf1a6beb35d)
![image](https://github.com/airbnb/mavericks/assets/16060581/c58fcb70-f99e-4467-b487-5e7e04ab1f44)
Does it support data of type abstract?

**Comment by artillerymans** [comment]
I think I should find the reason, because I use System.currentTimeMillis().toString(), the generated data is also no problem, but when it comes to a short period of time after calling setState millis often have a difference of plus or minus 1, this time will report an error If I put the value of the mills into the If I put the value of mills outside of setState, there is no such problem.
 `
val time = System.currentTimeMillis()
val uuid = UUID.UUID.randomUUID().toString()
setState {
    copy(
        time = time,
        or
        uuid = uuid
    )
}
`
