### ISSUE TITLE
Unable to resolve - hiltMavericksViewModelFactory

### ISSUE THREAD

**Issue by Veeresh8** [airbnb/mavericks#716]
From where do I get the dependency for - hiltMavericksViewModelFactory.
The docs do not have any reference to it.

**Comment by Veeresh8** [comment]
Do I need to copy the whole `mavericks-hilt` folder to my app? or is there a Gradle dependency that I can add?

**Comment by gpeal** [comment]
It's on Maven Central just like the main dependency
https://mvnrepository.com/artifact/com.airbnb.android/mavericks-hilt
