### ISSUE TITLE
Now the time has come to support multiple platforms?

### ISSUE THREAD

**Issue by artillerymans** [airbnb/mavericks#718]
The official documentation describes the lifecycle (*) library as having multi-platform support, so would it normally be possible to use this library directly on multiple platforms?

按照官方的文档描述 lifecycle (*) 库已经支持多平台，正常来说这个库是否就可以直接在多平台上使用？

https://developer.android.com/kotlin/multiplatform

**Comment by gpeal** [comment]
Other platforms have their own libraries. If you want to make a KMP library that calls this as an `expect fun`, you're welcome to.
